services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.halfred.app
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.halfred.app/
      - N8N_ENCRYPTION_KEY=change_me_to_a_long_random_string
    volumes:
      - ./.n8n:/home/node/.n8n
    restart: unless-stopped
